# Generated by Django 5.1 on 2024-08-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
