# Generated by Django 5.1 on 2024-08-20 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenges')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.users')),
            ],
            options={
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
