# Generated by Django 5.1 on 2024-08-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_url',
            field=models.URLField(),
        ),
    ]
