# Generated by Django 5.1 on 2024-08-21 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_audio_audio_url_alter_images_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='post_id',
            new_name='post',
        ),
    ]
