# Generated by Django 5.1 on 2024-08-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_rename_post_id_audio_post_rename_post_id_images_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
